config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :title, presence: true
  validates :content, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@post), notice: 'Comment was successfully created.'
    else
      render 'posts/show'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end
  def update
    puts "Params: #{params.inspect}"
    if @comment.update(comment_params)
      redirect_to post_path(@post), notice: 'Comment was successfully updated.'
    else
      puts "Errors: #{comment.errors.full_messages.inspect}"
      render :edit
    end
  end

  def destroy
    @comment.destroy!
    redirect_to post_path(@post), notice: 'Comment was successfully deleted.'
  end
  private

  def set_post
    @post = Post.find(params[:post_id])
  end
  def set_comment
    @comment = @post.comments.find(params[:id])
  end
  def comment_params
    params.require(:comment).permit(:title,:content)

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def show
      @comments = @post.comments
      @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post), notice: 'Post was successfully created.'
      else
        flash.now[:alert] = 'Error creating the post.'

      render :new
      end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post Updated"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title,:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<!-- app/views/comments/_comment.html.erb -->
<p><strong><%= comment.title %></strong>: <%= comment.content %></p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @post, @comment], local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, 'error') %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit 'Add Comment' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="mbox">
  <h1>Edit</h1>
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hydrogen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>

  <% if @post.new_record? %>
    <%= link_to 'Back', posts_path %>
  <% else %>
    <%= link_to 'Back', post_path(@post) %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class="mbox">
  <h1>Edit Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="mbox">
  <h1>All Posts!</h1>

    <ul>
      <% @posts.each do |post| %>
      <li>
        <%= link_to post.title, post_path(post)%>
      </li>
      <% end %>
    </ul>
    <%= link_to 'New Post', new_post_path %>

</div>

app/views/posts/new.html.erb
<div class="mbox">
  <h1>New Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="mbox">
  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>
<!--  <h3>Comments:</h3>-->
  <% @comments.each do |comment| %>
    <p><strong><%= comment.title %></strong>
      <%= comment.content %>
      <%= link_to "Edit ", edit_post_comment_path(@post, comment) %>
      <%= link_to "Delete", post_comment_path(@post,comment), data: { turbo_method: :delete } %></p>
  <% end %>
  <%= render partial: 'comments/form', locals: { comment: @comment } %>

  <p><%= link_to 'Edit', edit_post_path %></p>
  <!-- app/views/posts/show.html.erb -->
  <%= link_to "Delete", post_path(@post), data: { turbo_method: :delete } %>

  <%= link_to 'Back',posts_path %>
</div>